# Name of the workflow
name: Deploy my Lambda Function

# Triggers on push operation on the main branch only
on:
  push:
    branches:
      - main

# Defining the jobs
# Currently we are having only one job (build) that is to checkout the code on the runner, configure python on the runner
# For both of them, community action is being used. For python's community action version needs to be provided
# Next, in function folder an upgraded version of pip is installed first and then requirements.txt file is checked. If it is there it is installed
# Then, in the function folder a zip folder is beign created which is named on the GitHub commit SHA
# Finally the artifact is getting archive by the name of zipped-bundle onto the mentioned path for which again a community action is used
# This job will run on ubuntu latest version 
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with: 
          python-version: 3.8
      - name: Install required libraries
        run: |
            cd function
            python -m pip install --upgrade pip
            if [ -f requirements.txt ]; then pip install -r requirements.txt -t .; fi
      - name: Create a zip bundle 
        run: |
            cd function 
            zip -r ../${{ github.sha }}.zip .
      - name: Archive artifact
        uses: actions/upload-artifact@v2
        with:
          name: zipped-bundle
          path: ${{ github.sha }}.zip
          
            
          
